services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: rootpassword
      PGDATA: /data/postgres
      POSTGRES_DB: rocketseat_python
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg:/data/postgres