repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff-format

  # - repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
  #   rev: v1.13.0
  #   hooks:
  #       - id: basedpyright
  #         args: [src/]